import type { KeywordTopic } from "@/lib/marketing/article-gen";
import type { ZhPage } from "./types";

/**
 * The 30-topic Chinese content plan (docs/china-market/08). Each topic feeds
 * the trilingual article generator as a KeywordTopic: the Chinese keyword is
 * the primary target, the Thai/English keywords keep the TH/EN versions
 * useful, and `service` links the article to its /zh service page.
 *
 * `th` doubles as the dedupe key stored in marketing_articles.topic, so it
 * must be unique here AND distinct from article-gen.ts KEYWORD_TOPICS.
 */
export type ZhPillar = "R" | "B" | "F" | "D" | "I" | "S" | "H" | "L" | "$" | "P" | "T";

export interface ZhPlanTopic extends KeywordTopic {
  id: number;
  week: number;
  pillar: ZhPillar;
  /** Analytics/service key (ZhPage.service). */
  service: ZhPage["service"] | "pricing";
  /** Legal review required before publishing. */
  legalReview?: boolean;
}

export const ZH_PLAN_TOPICS: ZhPlanTopic[] = [
  { id: 1,  week: 3,  pillar: "H",  service: "general",       zh: "泰国侦探 靠谱",            th: "เลือกบริษัทสืบในไทยอย่างไรให้ไว้ใจได้", en: "how to vet an investigation company in Thailand", angle: "7 verification points a client abroad can check before hiring a Thai investigation company: registration, written quotation, scope, confidentiality, what they refuse to do, communication, report format." },
  { id: 2,  week: 3,  pillar: "R",  service: "relationship",  zh: "老公在泰国",                th: "คู่ครองทำงานหรือเรียนในไทย สงสัยควรเริ่มอย่างไร", en: "partner working or studying in Thailand — what to do when you have doubts", angle: "For a spouse living abroad: what to write down first, which facts can be verified lawfully, what an observation period looks like, and what a report can and cannot settle." },
  { id: 3,  week: 3,  pillar: "L",  service: "background",    zh: "泰国 侦探 能查什么",        th: "นักสืบไทยตรวจสอบอะไรได้บ้างตาม PDPA", en: "what a Thai investigator can legally find out (PDPA explained)", angle: "Plain explanation of Thailand's PDPA: public records vs restricted data, why no legitimate firm can obtain phone, bank, hotel or immigration records, and what lawful verification looks like.", legalReview: true },
  { id: 4,  week: 4,  pillar: "R",  service: "background",    zh: "泰国 婚前调查",            th: "เช็คประวัติก่อนแต่งงานกับคนในไทย", en: "pre-marriage verification in Thailand", angle: "Six things to verify before marrying someone living in Thailand: identity consistency, occupation, business ties, residence, public records, existing relationships — all through lawful channels." },
  { id: 5,  week: 4,  pillar: "$",  service: "pricing",       zh: "泰国私家侦探 费用",         th: "ค่าใช้จ่ายจ้างนักสืบในไทยคิดอย่างไร", en: "how investigation fees work in Thailand", angle: "Per-day vs per-project pricing, travel outside Bangkok, 50% deposit, what makes a case cheaper (good information, staged scope). No specific prices." },
  { id: 6,  week: 4,  pillar: "H",  service: "general",       zh: "泰国 调查 流程",            th: "ขั้นตอนจ้างนักสืบจากต่างประเทศ", en: "how to commission an investigation in Thailand remotely", angle: "The full remote workflow for an overseas client: WeChat/email consultation, assessment, written quote, deposit, progress updates, report delivery." },
  { id: 7,  week: 5,  pillar: "D",  service: "due_diligence", zh: "泰国 DBD 公司查询",         th: "ตรวจสอบบริษัทไทยจากข้อมูล DBD", en: "how to check a Thai company in the DBD registry", angle: "What Thailand's Department of Business Development public registry shows (status, capital, directors, filings), what it does not show, and why a site visit still matters." },
  { id: 8,  week: 5,  pillar: "S",  service: "on_site",       zh: "泰国 投资 骗局",            th: "สัญญาณเตือนโครงการอสังหาฯ การันตีผลตอบแทนในไทย", en: "red flags in guaranteed-return property schemes in Thailand", angle: "Five warning signs in 'guaranteed rental return' property offers aimed at foreign buyers and how on-site verification exposes them. No accusations of named projects." },
  { id: 9,  week: 5,  pillar: "L",  service: "general",       zh: "泰国 调查 合法吗",          th: "รายงานนักสืบใช้ในศาลได้ไหม", en: "can an investigator's report be used in court in Thailand", angle: "Basic concepts of admissibility, why lawful collection matters, the role of the lawyer; the report as a factual record, not a verdict. Recommend consulting a lawyer.", legalReview: true },
  { id: 10, week: 6,  pillar: "F",  service: "find_person",   zh: "泰国 失联",                 th: "ญาติหายตัวในไทย 48 ชั่วโมงแรกควรทำอะไร", en: "a relative has gone missing in Thailand — the first 48 hours", angle: "Checklist for families abroad: contact embassy and Thai police, gather last-known details, preserve chats, what an investigator can add in parallel. Safety first, no false promises." },
  { id: 11, week: 6,  pillar: "F",  service: "find_person",   zh: "泰国寻人",                  th: "ข้อมูลที่จำเป็นสำหรับการตามหาคนในไทย", en: "what information you need to find someone in Thailand", angle: "Which clues raise the odds: last city/area, photos, social accounts, employer, friends; how staged searches keep cost down; what success looks like and the person's right to privacy." },
  { id: 12, week: 6,  pillar: "P",  service: "general",       zh: "泰国 调查 准备",            th: "เตรียมข้อมูลอย่างไรก่อนจ้างนักสืบ", en: "how to prepare a case brief for an investigator", angle: "A case-brief checklist: objective, known facts, timeline, photos, documents, deadline, budget; what NOT to send (other people's ID numbers, bank data)." },
  { id: 13, week: 7,  pillar: "D",  service: "on_site",       zh: "泰国 供应商 核实",          th: "ตรวจสอบซัพพลายเออร์ไทยก่อนสั่งผลิต", en: "verifying a Thai supplier beyond the factory audit", angle: "What a buyer should verify besides capacity: legal entity, who actually owns the factory, address match, trade references, physical activity on an unannounced visit." },
  { id: 14, week: 7,  pillar: "B",  service: "background",    zh: "泰国 男友 背景调查",        th: "เช็คตัวตนคนรู้จักออนไลน์ที่อ้างว่าอยู่ไทย", en: "verifying an online acquaintance who says they live in Thailand", angle: "Romance-scam patterns targeting Chinese speakers, lawful identity-consistency checks, and when to walk away. Respectful tone, no shaming." },
  { id: 15, week: 7,  pillar: "T",  service: "on_site",       zh: "泰国 地址 核实",            th: "อ่านที่อยู่ไทยให้เข้าใจ Soi Moo Tambon", en: "how to read a Thai address (Soi, Moo, Tambon) and why it matters", angle: "Thai address structure explained for foreign clients; why the same road spans districts; how address verification is actually done on the ground." },
  { id: 16, week: 8,  pillar: "I",  service: "due_diligence", zh: "泰国 设厂 尽调",            th: "เช็กลิสต์ดีลิเจนซ์ก่อนตั้งโรงงานใน EEC", en: "due-diligence checklist before setting up a factory in Thailand's EEC", angle: "Land/park status, counterpart company checks, management background, local partner verification, on-site visits — from the Chonburi/Rayong perspective." },
  { id: 17, week: 8,  pillar: "$",  service: "pricing",       zh: "泰国 调查 需要多久",        th: "งานสืบแต่ละประเภทใช้เวลากี่วัน", en: "how long investigations take in Thailand by service type", angle: "Typical ranges only (verification days, observation periods, due-diligence weeks), what shortens or extends them. No guarantees." },
  { id: 18, week: 8,  pillar: "D",  service: "due_diligence", zh: "泰国 公司 背景调查",        th: "อ่านเอกสาร DBD ทุนจดทะเบียน กรรมการ งบการเงิน", en: "reading a Thai company file: capital, directors, annual filings", angle: "How to interpret registered capital, director lists, shareholder nationality and filing history; common misreadings by foreign counterparts." },
  { id: 19, week: 9,  pillar: "I",  service: "asset",         zh: "泰国 房产 核实",            th: "ตรวจสอบโครงการอสังหาฯ ไทยก่อนซื้อ", en: "verifying a Thai property investment: title type, developer, site status", angle: "Freehold vs leasehold basics, developer registry checks, site progress vs brochure, why formal title searches go through a lawyer.", legalReview: true },
  { id: 20, week: 9,  pillar: "S",  service: "on_site",       zh: "泰国 投资 核实",            th: "กรณีศึกษาตรวจสอบโครงการลงทุนผลตอบแทนสูงในไทย", en: "case study: on-site verification of a high-return investment pitch in Thailand", angle: "Anonymised, generic walkthrough of how an on-site verification is structured (objective → visit → evidence → conclusion). No real client, no identifying details." },
  { id: 21, week: 9,  pillar: "S",  service: "due_diligence", zh: "泰国 商业 诈骗 调查",       th: "ตรวจสอบบริษัทผู้รับเงินในไทยก่อนโอน 4 ขั้นตอน", en: "four checks before paying a Thai company you have never met", angle: "Registry match, bank-account-name consistency (as told by the counterpart, not via bank data), address visit, reference call; what to do if it is already paid." },
  { id: 22, week: 10, pillar: "R",  service: "relationship",  zh: "泰国 婚外情调查",           th: "ขอบเขตจริยธรรมของการสืบความสัมพันธ์ข้ามประเทศ", en: "the ethical boundaries of a relationship investigation", angle: "What a lawful observation includes and excludes (public places only, no devices, no contact, no private premises) and why those limits protect the client too." },
  { id: 23, week: 10, pillar: "H",  service: "general",       zh: "泰国 调查报告 样本",        th: "รายงานนักสืบหน้าตาเป็นอย่างไร", en: "what an investigation report looks like", angle: "Structure of a report: objective, scope/dates, method summary, timeline, photo evidence, sources, conclusion. Describe a redacted sample; invent nothing." },
  { id: 24, week: 10, pillar: "T",  service: "general",       zh: "曼谷调查",                  th: "ความต่างของงานสืบในกรุงเทพ พัทยา ภูเก็ต เชียงใหม่", en: "how investigations differ across Bangkok, Pattaya, Phuket and Chiang Mai", angle: "Practical differences: geography, traffic, tourist vs residential areas, seasonal costs, planning implications for each city." },
  { id: 25, week: 11, pillar: "B",  service: "background",    zh: "泰国 入职背景调查",         th: "ตรวจสอบประวัติพนักงานไทยก่อนจ้างทำได้แค่ไหน", en: "pre-employment background checks in Thailand: what employers may verify", angle: "Lawful employment screening: education, prior employers, public records, consent requirements under PDPA; what is off-limits.", legalReview: true },
  { id: 26, week: 11, pillar: "F",  service: "find_person",   zh: "泰国找人",                  th: "หลังตามหาคนเจอแล้ว ติดต่ออย่างไรให้ถูกกฎหมาย", en: "after the person is found: privacy, consent and lawful contact", angle: "Why a found adult's wishes are respected, how messages are relayed, service-of-process scenarios, when authorities are involved." },
  { id: 27, week: 11, pillar: "I",  service: "on_site",       zh: "泰国 酒店 投资 核实",       th: "ตรวจสอบโรงแรมหรือรีสอร์ตในไทยก่อนซื้อกิจการ", en: "on-site verification before buying a hotel or resort in Thailand", angle: "Occupancy reality vs claims, licences visible on site, staffing, condition, reviews consistency; what the investigator checks vs the lawyer/accountant." },
  { id: 28, week: 12, pillar: "L",  service: "general",       zh: "泰国 PDPA",                 th: "PDPA ไทยกับ PIPL จีน ข้อมูลส่วนบุคคลในการจ้างสืบข้ามประเทศ", en: "Thailand's PDPA and China's PIPL: personal-data limits in cross-border investigations", angle: "Side-by-side basics for a Chinese client hiring in Thailand: lawful bases, consent, what data may be collected and shared, retention.", legalReview: true },
  { id: 29, week: 12, pillar: "P",  service: "asset",         zh: "泰国 诉讼 证据",            th: "นักสืบช่วยเตรียมคดีร่วมกับทนายได้อย่างไร", en: "how an investigator supports your lawyer in litigation preparation", angle: "Asset leads, witness location, address confirmation for service, documented timelines; division of roles between investigator and lawyer." },
  { id: 30, week: 12, pillar: "H",  service: "general",       zh: "泰国 侦探 推荐",            th: "ทำไมบริการที่อ้างว่า 'สืบได้ทุกอย่าง' ไม่น่าเชื่อถือ", en: "why 'we can find anything' investigation services are a red flag", angle: "Common misconceptions; why lawful firms refuse certain requests; how over-promising signals risk to the client; what realistic scoping sounds like." },
];

/** Topics in schedule order (week, then id). */
export const ZH_PLAN_ORDERED: ZhPlanTopic[] = [...ZH_PLAN_TOPICS].sort((a, b) => a.week - b.week || a.id - b.id);
