import type { MarketingServicePage } from "./types";

/**
 * English service / info / location pages. Written for the foreign client's
 * actual questions (can I brief you from abroad, how do I pay, is it legal,
 * will the subject know, what do I receive). Same copy rules as th.ts.
 */
export const EN_SERVICE_PAGES: MarketingServicePage[] = [
  {
    lang: "en",
    slug: "cheating-spouse-investigator",
    kind: "service",
    service: "infidelity",
    title: "Infidelity Investigator Thailand — Cheating Partner Cases",
    description: "Discreet infidelity investigations across Thailand: lawful observation in public, timestamped photo and video, written report. Free consultation.",
    h1: "Infidelity & Cheating Partner Investigations in Thailand",
    eyebrow: "Case File · Infidelity",
    intro: "When you need facts rather than suspicion, our investigators observe a partner's movements discreetly in public places, document what they see with photos, video and timestamps, and deliver a written report you can act on — whether you are in Thailand or briefing us from abroad.",
    sections: [
      {
        heading: "Signs clients report before they contact us",
        body: ["No single sign proves anything. Clients usually call when several of these happen together and the explanations keep changing — and when watching for themselves would risk being noticed and spoiling any evidence."],
        bullets: [
          "Irregular hours with vague or shifting reasons",
          "A phone that is suddenly guarded, re-locked or answered in another room",
          "More \"work trips\" or weekends away than before",
          "Unexplained spending or a change in appearance",
          "A partner living in Thailand while you are overseas and the stories don't add up",
        ],
      },
      {
        heading: "How we work — and what we never do",
        body: [
          "We start from what you know: routine, workplace, vehicle, the places they say they go. We plan lawful observation in public places with a team sized for the area. We never enter private premises, never place a tracker on someone else's vehicle, never install software on anyone's phone, and never approach or confront the subject.",
          "During the assignment you receive updates on the schedule we agree (WhatsApp works well across time zones). At the end you receive a written report with photos, video and a dated, timed, located timeline.",
        ],
      },
      {
        heading: "Using the evidence in a Thai or foreign divorce",
        body: ["Lawfully obtained photos, video and timelines can support divorce proceedings or a claim against a third party in Thailand, and are routinely used by foreign lawyers as part of a wider case. Admissibility is always for the court to decide, so we recommend involving a lawyer early; we format reports so your lawyer can use them directly."],
      },
      {
        heading: "Timeline and pricing",
        body: ["Most infidelity assignments run 3–7 days of observation, chosen around the subject's routine. Pricing depends on days, team size, location and complexity. You receive a written quote before anything starts, pay a 50 % deposit, and settle the balance before the report is released. See the pricing page for how quotes are built."],
      },
    ],
    deliverables: [
      "Photos and video of the subject's movements, taken in public places",
      "A timeline with dates, times and locations",
      "A written factual report, formatted for your lawyer if needed",
      "Progress updates on the schedule you choose (WhatsApp or email)",
      "A short recommendation on next steps",
    ],
    notOffered: [
      "Pulling another person's call logs, messages or phone location",
      "GPS trackers on someone else's vehicle or spyware on their devices",
      "Access to private residences, hotel, airline or bank records",
      "Contact, pressure or confrontation with the subject",
    ],
    faq: [
      { q: "Will my partner know they are being followed?", a: "We work discreetly in public places and never approach the subject. No assignment is entirely risk-free, so we tell you honestly where the risks are before we start." },
      { q: "I'm abroad — can you really take the case?", a: "Yes. Most of our international clients brief us on WhatsApp or email, pay by bank transfer, receive updates in their time zone and get the report electronically." },
      { q: "How long does it take?", a: "Typically 3–7 days of observation, planned around the subject's routine and your objective. Some cases resolve sooner; some require watching specific dates." },
      { q: "Can the evidence be used in court?", a: "Lawfully obtained evidence from public places can support a case in Thailand or elsewhere, but admissibility is for the court. Involve a lawyer early; we format reports accordingly." },
      { q: "How confidential is this?", a: "Client identity and findings are kept strictly confidential, delivered through the channel you choose and deleted on the schedule we agree." },
    ],
    related: ["investigate-partner-before-marriage", "evidence-for-adultery-lawsuit", "pricing", "private-investigator-bangkok"],
    caseType: "Cheating spouse",
    priceNote: "Written quote before we start · 50 % deposit",
    counterpart: { th: "นักสืบชู้สาว", zh: "relationship-investigation" },
  },
  {
    lang: "en",
    slug: "investigate-partner-before-marriage",
    kind: "service",
    service: "partner",
    title: "Investigate a Thai Partner — Pre-Marriage Checks",
    description: "Verify a Thai partner or fiancé(e) before you commit: identity, relationship status, work and lifestyle checked lawfully from public sources.",
    h1: "Partner Verification in Thailand — Know Before You Commit",
    eyebrow: "Case File · Partner Verification",
    intro: "Long-distance relationships, a new partner met online, or a marriage planned across two countries: when the stakes are this high, verified facts beat hope. We check what a partner has told you against public sources, visits in person and discreet observation in public places, and report plainly — including when everything checks out.",
    sections: [
      {
        heading: "What a partner check can confirm (lawfully)",
        body: ["Everything below comes from open sources, field visits and observation in public places. Nothing comes from protected government or financial data."],
        bullets: [
          "Identity consistency: the name, age and story you were given against what is visible on the ground",
          "Relationship status and living situation as observed in daily life",
          "Where they actually live and work, confirmed by visiting",
          "Companies and directorships from Thailand's public business registry",
          "Public online footprint, duplicate or borrowed profiles",
          "Whether money you sent went where you were told",
        ],
      },
      {
        heading: "Common situations",
        body: [],
        bullets: [
          "You live abroad and your partner lives in Thailand; visits are short and stories keep shifting",
          "You met online and have sent money for family, medical or business reasons",
          "You plan to marry or buy property together and want an independent check first",
          "A second family, husband or wife has been hinted at by friends",
        ],
      },
      {
        heading: "How it works from abroad",
        body: ["Brief us on WhatsApp or email with what you know: name, photos, phone number, social accounts, home town, workplace, and the specific questions you need answered. We tell you honestly what can be verified and quote in writing. Most checks take a few days; observation assignments run longer. The report arrives electronically with photos and a timeline where relevant."],
      },
      {
        heading: "What we never do",
        body: ["We do not approach your partner, their family or friends, do not access anyone's phone or accounts, do not install trackers, and do not pull government or bank data. Any investigator who offers those things is breaking Thai law and putting you at risk too."],
      },
    ],
    deliverables: [
      "Written factual report separating what is confirmed from what is only observed",
      "Photos and a timeline from any observation in public places",
      "Consistency check of the identity and story you were given",
      "Updates during the assignment in your time zone",
      "A plain recommendation on next steps",
    ],
    notOffered: [
      "Civil registry, marriage registry or other government records",
      "Access to your partner's phone, chats or online accounts",
      "GPS trackers or spyware",
      "Contact with the subject or their family",
    ],
    faq: [
      { q: "Can you check whether my partner is already married?", a: "Marriage records are government data we do not access. We can establish relationship status from how they actually live and from public sources, and explain which official checks you may request yourself." },
      { q: "I only have a name and a Facebook profile. Is that enough?", a: "It is a starting point. A workplace, neighbourhood or recent photos make the check faster and more precise. Send everything you have and we assess for free." },
      { q: "Will my partner find out?", a: "We work in public places and never make contact. No assignment is entirely risk-free, and we tell you where the risks lie before we start." },
      { q: "How long does it take and what does it cost?", a: "Verification checks usually take a few days; observation runs 3–7 days. Cost depends on scope and location. You receive a written quote before anything starts." },
    ],
    related: ["cheating-spouse-investigator", "background-check", "pricing", "hire-a-private-detective"],
    caseType: "Cheating spouse",
    priceNote: "Free assessment · Written quote before we start",
    counterpart: { th: "จ้างนักสืบตามแฟน" },
  },
  {
    lang: "en",
    slug: "background-check",
    kind: "service",
    service: "background",
    title: "Background Check in Thailand — People & Companies",
    description: "Lawful background checks in Thailand on people and companies: identity, employment, litigation and directorships from public sources and field visits.",
    h1: "Background Checks in Thailand — Verify Before You Trust",
    eyebrow: "Case File · Background Check",
    intro: "Before you hire, invest, sign, lend or move in with someone in Thailand, an independent check reduces the risks that are hardest to undo. We verify from sources that are lawful to access, visit addresses in person, and report what is confirmed separately from what is merely indicated.",
    sections: [
      {
        heading: "What we can verify",
        body: ["All items come from open sources, documents you provide, field visits and observation in public places."],
        bullets: [
          "Identity consistency: name, date of birth and the story given, against what is visible in practice",
          "Employment and education as far as public sources and direct verification allow",
          "Litigation visible through Thailand's public court-judgment search and other open sources",
          "Company registrations, directorships and shareholdings from the public business registry",
          "Current address and workplace, confirmed by visiting",
          "Online footprint, fake or duplicate accounts and publicly visible behaviour",
        ],
      },
      {
        heading: "What no investigator can lawfully provide",
        body: ["Thailand's civil registry, social-security data, banking and credit data, travel history and telephone data are protected by law and available only to the data subject or by court order. Anyone selling them is committing an offence, and evidence obtained that way is unusable. Where you have a legal right to such data, we work with your lawyer to request it through proper channels."],
      },
      {
        heading: "Typical assignments",
        body: [],
        bullets: [
          "Pre-employment screening for positions of trust (with the candidate's consent, under Thailand's PDPA)",
          "Due diligence on a business partner, supplier or investment promoter",
          "Verifying a person met online before transferring money or meeting",
          "Checking a landlord, tenant or counterparty before signing",
          "Confirming a company at a registered address is actually operating",
        ],
      },
      {
        heading: "What to prepare and how long it takes",
        body: ["Full name (and former names), photos, phone or social accounts, province or district, stated workplace and the purpose of the check. Most background checks take a few working days depending on scope and field visits. You receive a written quote before we start."],
      },
    ],
    deliverables: [
      "Written factual report separating confirmed facts from indications",
      "Consistency assessment of the information the person provided",
      "Photos from field verification where relevant",
      "List of the sources used",
      "Recommendation on next steps",
    ],
    notOffered: [
      "Civil registry, social-security or other government database records",
      "Bank account, credit or blacklist data",
      "Another person's travel history or telephone data",
      "Hacking or accessing anyone's online accounts",
    ],
    faq: [
      { q: "Can you check someone from just a name?", a: "We can start, but Thai names are often shared. A photo, phone number, province or workplace makes the result far more reliable." },
      { q: "Can you check criminal records?", a: "We search publicly available court records. Official criminal-record certificates must be requested by the person concerned or through lawful procedures; we can explain the steps." },
      { q: "Can my company use this for hiring?", a: "Yes, with the candidate's consent and within what Thailand's PDPA allows. We help design a compliant process." },
      { q: "Is the result confidential?", a: "Client identity and findings are confidential and delivered through the channel you choose." },
    ],
    related: ["investigate-partner-before-marriage", "asset-investigation", "cyber-investigation", "pricing"],
    caseType: "Background check",
    priceNote: "Written quote before we start · 50 % deposit",
    counterpart: { th: "เช็คประวัติบุคคล", zh: "background-check" },
  },
  {
    lang: "en",
    slug: "find-missing-person",
    kind: "service",
    service: "find_person",
    title: "Find a Person in Thailand — Relatives, Debtors, Contacts",
    description: "Locate a person in Thailand: lost relatives, a partner who went silent, debtors or online scammers. Honest feasibility check, methodical search nationwide.",
    h1: "Finding a Person in Thailand — From a Name, a Photo or a Thread",
    eyebrow: "Case File · Find a Person",
    intro: "A relative you lost touch with, a Thai partner who went silent, a debtor who moved, or the person behind an online scam: we locate people across Thailand methodically, from open sources, local networks and field work, and tell you honestly from the start what the chances are.",
    sections: [
      {
        heading: "Who we are asked to find",
        body: [],
        bullets: [
          "Relatives, parents or children separated by time, migration or adoption",
          "A Thai partner or friend who stopped replying, to confirm they are safe or to re-establish contact",
          "Debtors or business counterparties who moved — we locate them so your lawyer can act; we never collect debts",
          "Sellers or individuals behind online scams, to support a police report",
          "People a lawyer needs to serve documents on",
        ],
      },
      {
        heading: "What helps us find them",
        body: ["Full name including former names and nicknames, photos, approximate age, home province, old phone numbers, social accounts, former address or employer, and anyone who might still know them. For online scams, keep every transfer slip, account number and conversation."],
      },
      {
        heading: "How we work",
        body: ["We start with an honest feasibility assessment. Then we search open sources and online traces, extend through local networks and field visits in the target province, and confirm any address or sighting by observation in public places before reporting. We do not access government databases and cannot promise a result in every case."],
      },
      {
        heading: "When to involve the police first",
        body: ["A child, an elderly or ill person, or anyone who may be in danger should be reported to the police immediately; there is no waiting period. Our work can complement an official search but never replaces it. Foreign nationals missing in Thailand can also be reported to their embassy."],
      },
    ],
    deliverables: [
      "Most recent address or whereabouts we can establish, with how it was verified",
      "Confirmation that the person found is the person sought",
      "Photos from field verification where relevant",
      "A report of the steps taken and the outcome",
      "Advice on next steps (contact, lawyer, police report)",
    ],
    notOffered: [
      "Civil registry, house registration or other government records",
      "Locating anyone through their phone or network operator data",
      "Debt collection, pressure or confrontation",
      "Locating people for purposes that threaten their safety",
    ],
    faq: [
      { q: "Can you find someone from just a name?", a: "Sometimes, but it is harder. We assess first whether the leads are enough to start, at no charge." },
      { q: "Do you guarantee a result?", a: "No. We work methodically, report every step and stop as soon as it is clear that continuing is not worth your money." },
      { q: "Will you contact the person for me?", a: "Only if you ask us to and it is appropriate. In most cases we confirm the location and let you, or your lawyer, make contact." },
      { q: "Can you work outside Bangkok?", a: "Yes, nationwide. Travel and accommodation outside Bangkok are itemised in the written quote." },
    ],
    related: ["background-check", "asset-investigation", "cyber-investigation", "private-investigator-bangkok"],
    caseType: "Find a person",
    priceNote: "Free feasibility assessment · Written quote before we start",
    counterpart: { th: "สืบตามหาคน", zh: "find-person-thailand" },
  },
  {
    lang: "en",
    slug: "asset-investigation",
    kind: "service",
    service: "asset",
    title: "Asset Investigation Thailand — Trace Property & Companies",
    description: "Asset tracing in Thailand before you sue or enforce a judgment: property, vehicle, company and income leads from lawful sources, formatted for your lawyer.",
    h1: "Asset Investigation in Thailand — Know What a Debtor Owns Before You Sue",
    eyebrow: "Case File · Asset Tracing",
    intro: "Winning a judgment you cannot enforce is a common and expensive outcome. Tracing assets before litigation or before enforcement lets you and your lawyer decide whether to sue or negotiate, and what can actually be seized. We find verifiable asset leads from lawful sources and field work and hand them to your lawyer for the steps that require the court.",
    sections: [
      {
        heading: "Assets we trace and how",
        body: [],
        bullets: [
          "Real estate: houses, condominiums and land — from field visits, listings and the land-office channels available to interested parties",
          "Vehicles in actual use — from observation in public places",
          "Businesses: companies, directorships and shareholdings — from Thailand's public business registry",
          "Income sources and current workplace — from field visits and open sources",
          "Signs of assets transferred after a demand or lawsuit — for your lawyer to consider a fraudulent-transfer claim",
        ],
      },
      {
        heading: "Working with your lawyer",
        body: ["Some data, such as full title deeds or bank accounts, is available only to interested parties through the court or the Legal Execution Department. Our job is to produce complete, verifiable leads so your lawyer can file precisely, saving time and cost at the enforcement stage. We routinely work with Thai and foreign law firms."],
      },
      {
        heading: "Before suing vs. after judgment",
        body: ["Before suing: to decide whether litigation is worthwhile, and to plan interim measures. After judgment: to identify assets for seizure or garnishment and follow assets moved out of reach. The method is the same; the report is shaped to the stage you are at."],
      },
      {
        heading: "Cost",
        body: ["Depends on the number of debtors, the area and the depth of verification. Law firms and lenders usually work with us per case. You receive a written quote before we start."],
      },
    ],
    deliverables: [
      "Itemised asset leads with sources and how to verify each",
      "Photos of property and premises from field visits",
      "Company and directorship data from public sources",
      "A report formatted for your lawyer to file with",
      "Recommended order of enforcement steps",
    ],
    notOffered: [
      "Bank balances or account transactions",
      "Credit data or government database records",
      "Seizure, garnishment or debt collection on your behalf",
      "Entering private land or residences",
    ],
    faq: [
      { q: "Can you find the debtor's bank accounts?", a: "No. Bank data is protected and reachable only through the court or the Legal Execution Department. We can identify which banks a debtor appears to use from open sources, so your lawyer can target a garnishment order." },
      { q: "The debtor has already transferred assets. What now?", a: "We trace the transfers and the recipients so your lawyer can assess a claim to set the transfers aside under Thai law." },
      { q: "How long does it take?", a: "An initial asset trace usually takes a few days to two weeks depending on the area and the number of assets to verify." },
      { q: "Do you work with foreign law firms?", a: "Yes, regularly. We brief and report in English and format reports for use in Thai enforcement proceedings." },
    ],
    related: ["find-missing-person", "background-check", "pricing", "hire-a-private-detective"],
    caseType: "Asset search",
    priceNote: "Per-case written quote · 50 % deposit",
    counterpart: { th: "สืบทรัพย์สิน", zh: "asset-investigation" },
  },
  {
    lang: "en",
    slug: "cyber-investigation",
    kind: "service",
    service: "cyber",
    title: "Online Investigation Thailand — Scams & Fake Profiles",
    description: "Lawful online investigations in Thailand: verify who is behind a profile, trace online scammers, organise digital evidence. Open sources only, no hacking.",
    h1: "Cyber & Online Investigations — Within the Law",
    eyebrow: "Case File · Online Investigation",
    intro: "Who is really behind the profile you are talking to? Is the account that messaged you genuine? Where did the money you sent end up? We answer these questions with open-source intelligence (OSINT) and analysis of publicly visible digital traces, without hacking, interception or access to anyone's accounts.",
    sections: [
      {
        heading: "What we take on",
        body: [],
        bullets: [
          "Verifying whether a social-media account is genuine, fake or using stolen photos",
          "Tracing the people behind online scams from accounts, numbers and public data, to support a police report",
          "Checking unknown phone numbers against public scam reports",
          "Organising online evidence (screenshots, links, timestamps) so it is traceable and usable",
          "Reviewing the publicly visible online behaviour of a person or business",
        ],
      },
      {
        heading: "Legal boundaries",
        body: ["We use only information that is publicly visible or that you own. We do not guess passwords, send phishing links, intercept messages or buy data from illegal sources. Those acts breach Thailand's Computer Crime Act and PDPA and would make any evidence unusable."],
      },
      {
        heading: "Scammed online? Do this first",
        body: ["Contact your bank immediately to try to freeze onward transfers; in Thailand the anti-online-scam hotline is 1441. Keep every piece of evidence: slips, conversations, profiles, numbers and destination accounts. File a police report (Thai Police online reporting is available). We then help trace the people involved to strengthen the case."],
      },
    ],
    deliverables: [
      "Identity-verification report and account linkage analysis",
      "Organised online evidence with timestamps and sources",
      "Summary of the traces found from open sources",
      "Advice on reporting and on preventing a repeat",
    ],
    notOffered: [
      "Hacking, password guessing or access to anyone's accounts",
      "Message interception or telephone data from operators",
      "Locating another person's phone",
      "Buying personal data from illegal sources",
    ],
    faq: [
      { q: "Can you identify an online scammer?", a: "In many cases we can trace accounts, numbers and public data far enough to help the case, but we cannot promise identification every time. We assess first." },
      { q: "Can you get my money back?", a: "Freezing and recovering funds is a process run by banks and the authorities. We strengthen that process with evidence and traces." },
      { q: "Can you tell whether a profile is a real person?", a: "Yes. We analyse photo consistency, posting history, network and other open data and give a reasoned opinion." },
      { q: "Can you check my partner's Facebook or LINE?", a: "Only what is publicly visible. We never access another person's private accounts. For behaviour, see our infidelity service, which works lawfully in public places." },
    ],
    related: ["find-missing-person", "background-check", "investigate-partner-before-marriage", "pricing"],
    caseType: "Cyber / online",
    priceNote: "Free assessment · Written quote before we start",
    counterpart: { th: "นักสืบไอที" },
  },
  {
    lang: "en",
    slug: "hire-a-private-detective",
    kind: "info",
    service: "hire",
    title: "Hire a Private Detective in Thailand — How It Works",
    description: "How to hire a private investigator in Thailand from abroad or locally: the 8-step process, what to prepare, payment, and signs of a fake detective.",
    h1: "How to Hire a Private Detective in Thailand",
    eyebrow: "Case File · Hiring Guide",
    intro: "Hiring an investigator for the first time, often from another country, raises practical questions: where to start, what to share, how to pay safely, and how to tell a genuine agency from a scam. This page walks through our whole process and the warning signs worth knowing before you send money to anyone.",
    sections: [
      {
        heading: "The 8-step process",
        body: [],
        bullets: [
          "Contact us on WhatsApp, email or the form — free and without obligation. Describe the situation and what you need to know.",
          "We assess feasibility and the lawful scope, honestly, including when we think the case is not worth your money.",
          "You receive a written quote with scope, timeline and what is included.",
          "A 50 % deposit by bank transfer confirms the start.",
          "We plan the assignment: team, days, locations, and how you want updates.",
          "Field work and research run; you receive updates on the agreed schedule, in your time zone.",
          "You settle the balance and receive the report with photos, video and a timeline, electronically.",
          "We advise on next steps and, where useful, brief your lawyer.",
        ],
      },
      {
        heading: "What to prepare",
        body: ["The subject's name and photos, address or neighbourhood, workplace, vehicle, approximate routine, what you suspect and what you need to know, and your end goal (legal action, negotiation, or simply the truth). These shape the plan and the price."],
      },
      {
        heading: "Six warning signs of a fake or unlawful investigator",
        body: [],
        bullets: [
          "Promises to \"check anything\", including bank, phone or government data on other people",
          "Demands full payment before discussing details, or pressure to pay immediately",
          "No verifiable presence: no reviews on an independent platform, no video call",
          "Guarantees of a result or of \"catching them for sure\"",
          "Prices far below what the days and people required would cost",
          "Suggests unlawful methods such as trackers on other people's cars or phone hacking",
        ],
      },
      {
        heading: "How to check us",
        body: ["Read our identity-verified reviews on Fastwork, note that this site has run in Thai, English and Chinese for years, ask for a video call before starting, and always ask for a written quote. We say plainly when something cannot be done lawfully or is not worth the cost."],
      },
    ],
    deliverables: [
      "Written quote before anything starts",
      "A clear plan and timeline",
      "Updates during the assignment in your time zone",
      "Factual report with evidence, formatted for a lawyer when needed",
    ],
    faq: [
      { q: "Is the first consultation free?", a: "Yes. Feasibility and scope are assessed free of charge before we quote." },
      { q: "Do I need to be in Thailand?", a: "No. Most international clients brief us on WhatsApp or email, pay by transfer and receive the report electronically. A meeting in Bangkok or a video call is available if you prefer." },
      { q: "How do I pay from abroad?", a: "International bank transfer is standard; we provide the details with the written quote. We never ask for payment in gift cards or crypto." },
      { q: "Can I cancel?", a: "Yes, but the deposit is non-refundable once field work has started. This is stated in every quote." },
    ],
    related: ["pricing", "cheating-spouse-investigator", "background-check", "private-investigator-bangkok"],
    caseType: "Other",
    priceNote: "Free consultation · Written quote before we start",
    counterpart: { th: "จ้างนักสืบ" },
  },
  {
    lang: "en",
    slug: "pricing",
    kind: "info",
    service: "pricing",
    title: "Private Investigator Cost in Thailand — How Pricing Works",
    description: "What a private investigator costs in Thailand depends on case type, days, team and location. Our pricing structure, 50 % deposit and how to get a quote.",
    h1: "Private Investigator Pricing in Thailand — A Transparent Structure",
    eyebrow: "Case File · Pricing",
    intro: "\"It depends\" does not help you decide. This page explains what our price is made of, which factors push it up or down, and how you get a firm written quote in the first conversation.",
    sections: [
      {
        heading: "What determines the price",
        body: [],
        bullets: [
          "Case type: observation uses more people and time than research-based verification",
          "Days or hours of observation required, and when (nights, weekends)",
          "Number of investigators needed to keep the assignment safe and unnoticed",
          "Location: Bangkok and its suburbs versus provinces with travel and accommodation",
          "Complexity, such as a cautious subject or several locations to verify",
        ],
      },
      {
        heading: "Payment and terms",
        body: ["A written quote is issued before every assignment. A 50 % deposit confirms the start and the balance is settled before the report is released. If the client cancels after field work has begun, the deposit is not refunded because the team has already deployed. Field costs driven by the subject's behaviour, such as venue entry, are agreed in advance as included or itemised."],
      },
      {
        heading: "What is included",
        body: [],
        bullets: [
          "Planning and a team sized to the agreed scope",
          "Observation or verification for the days specified",
          "Progress updates during the assignment",
          "A factual report with photos, video and a timeline",
          "A follow-up conversation about next steps after the report",
        ],
      },
      {
        heading: "Why a very low price is a warning sign",
        body: ["Safe observation needs at least one or two people per day with a vehicle. A price below that cost usually means work that is not actually done, or methods that break the law, which make the evidence unusable and can expose you to liability."],
      },
      {
        heading: "Paying from abroad",
        body: ["International bank transfer is standard. Details come with the written quote. We never ask for payment by gift card or cryptocurrency, and we never ask for full payment before the quote is agreed."],
      },
    ],
    faq: [
      { q: "Can you give a rough price on chat?", a: "Yes, once we know the case type, location and approximate days. A firm written quote follows once we have the full picture." },
      { q: "Are there hidden costs?", a: "No. Every cost that may arise is listed in the quote as included or itemised." },
      { q: "Which payment methods do you accept?", a: "Bank transfer, domestic or international. Other options can be discussed when the assignment is agreed." },
      { q: "If you find nothing, do I still pay in full?", a: "Yes. You pay for the work performed to plan, not for a particular result. A \"nothing found\" result is equally valuable information, and we never embellish findings to make an assignment look worthwhile." },
    ],
    related: ["hire-a-private-detective", "cheating-spouse-investigator", "asset-investigation", "contact"],
    caseType: "Other",
    priceNote: "Free quote · 50 % deposit · No hidden costs",
    counterpart: { th: "ราคานักสืบ", zh: "pricing" },
  },
  {
    lang: "en",
    slug: "private-investigator-bangkok",
    kind: "location",
    service: "location",
    title: "Private Investigator in Bangkok — Local Team, Fast Start",
    description: "Bangkok-based private investigators covering every district and nearby provinces: infidelity, background checks, locating people, asset tracing.",
    h1: "Private Investigator in Bangkok — A Resident Team That Knows the City",
    eyebrow: "Location · Bangkok",
    intro: "Bangkok is where we work every day. A resident team that knows the districts, routes and traffic rhythms plans observation more precisely and starts faster than anywhere else. We cover all Bangkok districts and the surrounding provinces of Nonthaburi, Pathum Thani and Samut Prakan.",
    sections: [
      {
        heading: "Assignments we handle most in Bangkok",
        body: [],
        bullets: [
          "Infidelity and behaviour observation in business and residential districts",
          "Background checks on employees, partners and counterparties based in Bangkok",
          "Locating the current address of a debtor or a person a lawyer needs to serve",
          "Confirming that a company registered at an office address actually operates",
          "Verifying people met online who say they live or work in Bangkok",
        ],
      },
      {
        heading: "Areas we cover daily",
        body: ["Sukhumvit, Silom, Sathorn, Ratchada, Lat Phrao, Ramkhamhaeng, Bang Na, the Thonburi side and the surrounding provinces. Work around gated condominiums and housing estates is done from public areas only, and rush-hour traffic is built into the plan from the start."],
      },
      {
        heading: "How fast can you start?",
        body: ["Research-based verification starts as soon as the assignment is agreed. Most field assignments in Bangkok can be staffed within 1–2 working days; ask about urgent cases. You can meet us in Bangkok to discuss details or brief us on WhatsApp from anywhere."],
      },
      {
        heading: "Outside Bangkok and nationwide",
        body: ["We take assignments in every province, with travel and accommodation itemised in the quote. Cases where the subject moves between Bangkok and the provinces are planned as one continuous assignment."],
      },
    ],
    deliverables: [
      "A plan that accounts for real districts and traffic",
      "A resident team that deploys quickly",
      "Factual report with photos, video and timeline",
      "Choice of an in-person meeting in Bangkok or a fully remote briefing",
    ],
    notOffered: [
      "Entering condominiums, housing estates or other private premises",
      "GPS trackers or devices on other people's property",
      "Access to government, bank or telephone data on other people",
    ],
    faq: [
      { q: "Do you only cover Bangkok?", a: "No, we work nationwide, but Bangkok and its suburbs start fastest because the team is resident." },
      { q: "The subject lives in a guarded condominium. Can you still work?", a: "Yes, by observing from public areas around the building and its access routes. We never enter private premises." },
      { q: "Can we meet in person?", a: "Yes, in Bangkok at a place convenient for you, or we can start on WhatsApp or a video call right away." },
      { q: "Are the suburbs priced like Bangkok?", a: "Generally yes. Some outer areas carry a small travel charge, which is stated in the quote." },
    ],
    related: ["cheating-spouse-investigator", "background-check", "find-missing-person", "pricing"],
    caseType: "Other",
    priceNote: "Bangkok rates · Written quote before we start",
    counterpart: { th: "นักสืบกรุงเทพ", zh: "bangkok" },
  },
  {
    lang: "en",
    slug: "about",
    kind: "info",
    service: "about",
    title: "About Us — Private Investigators in Thailand Since 2016",
    description: "A Thai private investigation agency working within the law since 2016 for individuals, lawyers and businesses, in Thai, English and Chinese, nationwide.",
    h1: "Who We Are and How We Work",
    eyebrow: "Dossier · About",
    intro: "Detective Pulse has provided private investigation services in Thailand since 2016 for individuals, lawyers and businesses, many of them abroad. We believe good investigative work must be lawful, verifiable and reported honestly — including when the finding is \"nothing unusual\".",
    sections: [
      {
        heading: "What we do",
        body: ["Infidelity and behaviour observation, background checks, locating people, asset tracing, online investigations and company verification. The core team is based in Bangkok and we take assignments nationwide."],
      },
      {
        heading: "How we work",
        body: [],
        bullets: [
          "Lawfully: observation in public places, open sources, field visits and documents provided by the client only, in line with Thailand's PDPA",
          "Honestly: we assess feasibility before accepting a case and decline work that cannot or should not be done",
          "Verifiably: every report records dates, times, places and sources",
          "Confidentially: client identity and findings are accessible only to the team responsible",
          "Without guarantees of outcome: we sell work to plan, not promises we cannot keep",
        ],
      },
      {
        heading: "Working with international clients",
        body: ["Most overseas clients brief us on WhatsApp or email, pay by international transfer, receive updates in their time zone and get the report electronically. We work in English, Thai and Chinese and regularly support foreign lawyers with Thai evidence."],
      },
      {
        heading: "How to check us",
        body: ["Read our identity-verified reviews on Fastwork, note that this site has run in three languages for years, ask for a video call before starting, and always ask for a written quote. If someone uses our name but proposes unlawful methods, it is not us."],
      },
    ],
    faq: [
      { q: "Do you have an office I can visit?", a: "Our investigators work primarily in the field. Case discussions are arranged at the client's convenience — online, by phone or in person in Bangkok." },
      { q: "Do you work outside Bangkok?", a: "Yes, nationwide, with travel and accommodation itemised in the quote." },
      { q: "Do you work with lawyers and companies?", a: "Yes, they are a key client group, especially for asset tracing, locating people and background checks." },
      { q: "How long do you keep client data?", a: "Only as long as the assignment and our agreement require; it is deleted on schedule or on request within the law." },
    ],
    related: ["hire-a-private-detective", "pricing", "private-investigator-bangkok", "contact"],
    caseType: "Other",
    priceNote: "Free consultation · Confidential",
    counterpart: { th: "เกี่ยวกับเรา", zh: "about" },
  },
];
