import type { MarketingServicePage } from "./types";
import { FACTS, officeAnswer, paymentMethodsText } from "@/lib/marketing/facts";

const YEAR = FACTS.confirmed.foundingYear;

/**
 * English service / info / location pages. Written for the foreign client's
 * actual questions (can I brief you from abroad, how do I pay, is it legal,
 * will the subject know, what do I receive). Same copy rules as th.ts.
 */
export const EN_SERVICE_PAGES: MarketingServicePage[] = [
  {
    lang: "en",
    slug: "cheating-spouse-investigator",
    kind: "service",
    service: "infidelity",
    title: "Infidelity Investigator Thailand — Cheating Partner Cases",
    description: "Discreet infidelity investigations across Thailand: lawful observation in public, timestamped photo and video, written report. Free consultation.",
    h1: "Infidelity & Cheating Partner Investigations in Thailand",
    eyebrow: "Case File · Infidelity",
    intro: "When you need facts rather than suspicion, our investigators observe a partner's movements discreetly in public places, document what they see with photos, video and timestamps, and deliver a written report you can act on — whether you are in Thailand or briefing us from abroad.",
    sections: [
      {
        heading: "Signs clients report before they contact us",
        body: ["No single sign proves anything. Clients usually call when several of these happen together and the explanations keep changing — and when watching for themselves would risk being noticed and spoiling any evidence."],
        bullets: [
          "Irregular hours with vague or shifting reasons",
          "A phone that is suddenly guarded, re-locked or answered in another room",
          "More \"work trips\" or weekends away than before",
          "Unexplained spending or a change in appearance",
          "A partner living in Thailand while you are overseas and the stories don't add up",
        ],
      },
      {
        heading: "How we work — and what we never do",
        body: [
          "We start from what you know: routine, workplace, vehicle, the places they say they go. We plan lawful observation in public places with a team sized for the area. We never enter private premises, never place a tracker on someone else's vehicle, never install software on anyone's phone, and never approach or confront the subject.",
          "During the assignment you receive updates on the schedule we agree (WhatsApp works well across time zones). At the end you receive a written report with photos, video and a dated, timed, located timeline.",
        ],
      },
      {
        heading: "Using the evidence in a Thai or foreign divorce",
        body: ["Lawfully obtained photos, video and timelines can support divorce proceedings or a claim against a third party in Thailand, and are routinely used by foreign lawyers as part of a wider case. Admissibility is always for the court to decide, so we recommend involving a lawyer early; we format reports so your lawyer can use them directly."],
      },
      {
        heading: "Timeline and pricing",
        body: ["Most infidelity assignments run 3–7 days of observation, chosen around the subject's routine. Pricing depends on days, team size, location and complexity. You receive a written quote before anything starts, pay a 50 % deposit, and settle the balance before the report is released. See the pricing page for how quotes are built."],
      },
    ],
    deliverables: [
      "Photos and video of the subject's movements, taken in public places",
      "A timeline with dates, times and locations",
      "A written factual report, formatted for your lawyer if needed",
      "Progress updates on the schedule you choose (WhatsApp or email)",
      "A short recommendation on next steps",
    ],
    notOffered: [
      "Pulling another person's call logs, messages or phone location",
      "GPS trackers on someone else's vehicle or spyware on their devices",
      "Access to private residences, hotel, airline or bank records",
      "Contact, pressure or confrontation with the subject",
    ],
    faq: [
      { q: "Will my partner know they are being followed?", a: "We work discreetly in public places and never approach the subject. No assignment is entirely risk-free, so we tell you honestly where the risks are before we start." },
      { q: "I'm abroad — can you really take the case?", a: "Yes. Most of our international clients brief us on WhatsApp or email, pay by bank transfer, receive updates in their time zone and get the report electronically." },
      { q: "How long does it take?", a: "Typically 3–7 days of observation, planned around the subject's routine and your objective. Some cases resolve sooner; some require watching specific dates." },
      { q: "Can the evidence be used in court?", a: "Lawfully obtained evidence from public places can support a case in Thailand or elsewhere, but admissibility is for the court. Involve a lawyer early; we format reports accordingly." },
      { q: "How confidential is this?", a: "Client identity and findings are kept strictly confidential, delivered through the channel you choose and deleted on the schedule we agree." },
    ],
    related: ["investigate-partner-before-marriage", "evidence-for-adultery-lawsuit", "pricing", "private-investigator-bangkok"],
    caseType: "Cheating spouse",
    priceNote: "Written quote before we start · 50 % deposit",
    counterpart: { th: "นักสืบชู้สาว", zh: "relationship-investigation" },
  },
  {
    lang: "en",
    slug: "investigate-partner-before-marriage",
    kind: "service",
    service: "partner",
    title: "Investigate a Thai Partner — Pre-Marriage Checks",
    description: "Verify a Thai partner or fiancé(e) before you commit: identity, relationship status, work and lifestyle checked lawfully from public sources.",
    h1: "Partner Verification in Thailand — Know Before You Commit",
    eyebrow: "Case File · Partner Verification",
    intro: "Long-distance relationships, a new partner met online, or a marriage planned across two countries: when the stakes are this high, verified facts beat hope. We check what a partner has told you against public sources, visits in person and discreet observation in public places, and report plainly — including when everything checks out.",
    sections: [
      {
        heading: "What a partner check can confirm (lawfully)",
        body: ["Everything below comes from open sources, field visits and observation in public places. Nothing comes from protected government or financial data."],
        bullets: [
          "Identity consistency: the name, age and story you were given against what is visible on the ground",
          "Relationship status and living situation as observed in daily life",
          "Where they actually live and work, confirmed by visiting",
          "Companies and directorships from Thailand's public business registry",
          "Public online footprint, duplicate or borrowed profiles",
          "Whether money you sent went where you were told",
        ],
      },
      {
        heading: "Common situations",
        body: [],
        bullets: [
          "You live abroad and your partner lives in Thailand; visits are short and stories keep shifting",
          "You met online and have sent money for family, medical or business reasons",
          "You plan to marry or buy property together and want an independent check first",
          "A second family, husband or wife has been hinted at by friends",
        ],
      },
      {
        heading: "How it works from abroad",
        body: ["Brief us on WhatsApp or email with what you know: name, photos, phone number, social accounts, home town, workplace, and the specific questions you need answered. We tell you honestly what can be verified and quote in writing. Most checks take a few days; observation assignments run longer. The report arrives electronically with photos and a timeline where relevant."],
      },
      {
        heading: "What we never do",
        body: ["We do not approach your partner, their family or friends, do not access anyone's phone or accounts, do not install trackers, and do not pull government or bank data. Any investigator who offers those things is breaking Thai law and putting you at risk too."],
      },
    ],
    deliverables: [
      "Written factual report separating what is confirmed from what is only observed",
      "Photos and a timeline from any observation in public places",
      "Consistency check of the identity and story you were given",
      "Updates during the assignment in your time zone",
      "A plain recommendation on next steps",
    ],
    notOffered: [
      "Civil registry, marriage registry or other government records",
      "Access to your partner's phone, chats or online accounts",
      "GPS trackers or spyware",
      "Contact with the subject or their family",
    ],
    faq: [
      { q: "Can you check whether my partner is already married?", a: "Marriage records are government data we do not access. We can establish relationship status from how they actually live and from public sources, and explain which official checks you may request yourself." },
      { q: "I only have a name and a Facebook profile. Is that enough?", a: "It is a starting point. A workplace, neighbourhood or recent photos make the check faster and more precise. Send everything you have and we assess for free." },
      { q: "Will my partner find out?", a: "We work in public places and never make contact. No assignment is entirely risk-free, and we tell you where the risks lie before we start." },
      { q: "How long does it take and what does it cost?", a: "Verification checks usually take a few days; observation runs 3–7 days. Cost depends on scope and location. You receive a written quote before anything starts." },
    ],
    related: ["cheating-spouse-investigator", "background-check", "pricing", "hire-a-private-detective"],
    caseType: "Cheating spouse",
    priceNote: "Free assessment · Written quote before we start",
    counterpart: { th: "จ้างนักสืบตามแฟน" },
  },
  {
    lang: "en",
    slug: "background-check",
    kind: "service",
    service: "background",
    title: "Background Check in Thailand — People & Companies",
    description: "Lawful background checks in Thailand on people and companies: identity, employment, litigation and directorships from public sources and field visits.",
    h1: "Background Checks in Thailand — Verify Before You Trust",
    eyebrow: "Case File · Background Check",
    intro: "Before you hire, invest, sign, lend or move in with someone in Thailand, an independent check reduces the risks that are hardest to undo. We verify from sources that are lawful to access, visit addresses in person, and report what is confirmed separately from what is merely indicated.",
    sections: [
      {
        heading: "What we can verify",
        body: ["All items come from open sources, documents you provide, field visits and observation in public places."],
        bullets: [
          "Identity consistency: name, date of birth and the story given, against what is visible in practice",
          "Employment and education as far as public sources and direct verification allow",
          "Litigation visible through Thailand's public court-judgment search and other open sources",
          "Company registrations, directorships and shareholdings from the public business registry",
          "Current address and workplace, confirmed by visiting",
          "Online footprint, fake or duplicate accounts and publicly visible behaviour",
        ],
      },
      {
        heading: "What no investigator can lawfully provide",
        body: ["Thailand's civil registry, social-security data, banking and credit data, travel history and telephone data are protected by law and available only to the data subject or by court order. Anyone selling them is committing an offence, and evidence obtained that way is unusable. Where you have a legal right to such data, we work with your lawyer to request it through proper channels."],
      },
      {
        heading: "Typical assignments",
        body: [],
        bullets: [
          "Pre-employment screening for positions of trust (with the candidate's consent, under Thailand's PDPA)",
          "Due diligence on a business partner, supplier or investment promoter",
          "Verifying a person met online before transferring money or meeting",
          "Checking a landlord, tenant or counterparty before signing",
          "Confirming a company at a registered address is actually operating",
        ],
      },
      {
        heading: "What to prepare and how long it takes",
        body: ["Full name (and former names), photos, phone or social accounts, province or district, stated workplace and the purpose of the check. Most background checks take a few working days depending on scope and field visits. You receive a written quote before we start."],
      },
    ],
    deliverables: [
      "Written factual report separating confirmed facts from indications",
      "Consistency assessment of the information the person provided",
      "Photos from field verification where relevant",
      "List of the sources used",
      "Recommendation on next steps",
    ],
    notOffered: [
      "Civil registry, social-security or other government database records",
      "Bank account, credit or blacklist data",
      "Another person's travel history or telephone data",
      "Hacking or accessing anyone's online accounts",
    ],
    faq: [
      { q: "Can you check someone from just a name?", a: "We can start, but Thai names are often shared. A photo, phone number, province or workplace makes the result far more reliable." },
      { q: "Can you check criminal records?", a: "We search publicly available court records. Official criminal-record certificates must be requested by the person concerned or through lawful procedures; we can explain the steps." },
      { q: "Can my company use this for hiring?", a: "Yes, with the candidate's consent and within what Thailand's PDPA allows. We help design a compliant process." },
      { q: "Is the result confidential?", a: "Client identity and findings are confidential and delivered through the channel you choose." },
    ],
    related: ["investigate-partner-before-marriage", "asset-investigation", "cyber-investigation", "pricing"],
    caseType: "Background check",
    priceNote: "Written quote before we start · 50 % deposit",
    counterpart: { th: "เช็คประวัติบุคคล", zh: "background-check" },
  },
  {
    lang: "en",
    slug: "find-missing-person",
    kind: "service",
    service: "find_person",
    title: "Find a Person in Thailand — Relatives, Debtors, Contacts",
    description: "Locate a person in Thailand: lost relatives, a partner who went silent, debtors or online scammers. Honest feasibility check, methodical search nationwide.",
    h1: "Finding a Person in Thailand — From a Name, a Photo or a Thread",
    eyebrow: "Case File · Find a Person",
    intro: "A relative you lost touch with, a Thai partner who went silent, a debtor who moved, or the person behind an online scam: we locate people across Thailand methodically, from open sources, local networks and field work, and tell you honestly from the start what the chances are.",
    sections: [
      {
        heading: "Who we are asked to find",
        body: [],
        bullets: [
          "Relatives, parents or children separated by time, migration or adoption",
          "A Thai partner or friend who stopped replying, to confirm they are safe or to re-establish contact",
          "Debtors or business counterparties who moved — we locate them so your lawyer can act; we never collect debts",
          "Sellers or individuals behind online scams, to support a police report",
          "People a lawyer needs to serve documents on",
        ],
      },
      {
        heading: "What helps us find them",
        body: ["Full name including former names and nicknames, photos, approximate age, home province, old phone numbers, social accounts, former address or employer, and anyone who might still know them. For online scams, keep every transfer slip, account number and conversation."],
      },
      {
        heading: "How we work",
        body: ["We start with an honest feasibility assessment. Then we search open sources and online traces, extend through local networks and field visits in the target province, and confirm any address or sighting by observation in public places before reporting. We do not access government databases and cannot promise a result in every case."],
      },
      {
        heading: "When to involve the police first",
        body: ["A child, an elderly or ill person, or anyone who may be in danger should be reported to the police immediately; there is no waiting period. Our work can complement an official search but never replaces it. Foreign nationals missing in Thailand can also be reported to their embassy."],
      },
    ],
    deliverables: [
      "Most recent address or whereabouts we can establish, with how it was verified",
      "Confirmation that the person found is the person sought",
      "Photos from field verification where relevant",
      "A report of the steps taken and the outcome",
      "Advice on next steps (contact, lawyer, police report)",
    ],
    notOffered: [
      "Civil registry, house registration or other government records",
      "Locating anyone through their phone or network operator data",
      "Debt collection, pressure or confrontation",
      "Locating people for purposes that threaten their safety",
    ],
    faq: [
      { q: "Can you find someone from just a name?", a: "Sometimes, but it is harder. We assess first whether the leads are enough to start, at no charge." },
      { q: "Do you guarantee a result?", a: "No. We work methodically, report every step and stop as soon as it is clear that continuing is not worth your money." },
      { q: "Will you contact the person for me?", a: "Only if you ask us to and it is appropriate. In most cases we confirm the location and let you, or your lawyer, make contact." },
      { q: "Can you work outside Bangkok?", a: "Yes, nationwide. Travel and accommodation outside Bangkok are itemised in the written quote." },
    ],
    related: ["background-check", "asset-investigation", "cyber-investigation", "private-investigator-bangkok"],
    caseType: "Find a person",
    priceNote: "Free feasibility assessment · Written quote before we start",
    counterpart: { th: "สืบตามหาคน", zh: "find-person-thailand" },
  },
  {
    lang: "en",
    slug: "asset-investigation",
    kind: "service",
    service: "asset",
    title: "Asset Investigation Thailand — Trace Property & Companies",
    description: "Asset tracing in Thailand before you sue or enforce a judgment: property, vehicle, company and income leads from lawful sources, formatted for your lawyer.",
    h1: "Asset Investigation in Thailand — Know What a Debtor Owns Before You Sue",
    eyebrow: "Case File · Asset Tracing",
    intro: "Winning a judgment you cannot enforce is a common and expensive outcome. Tracing assets before litigation or before enforcement lets you and your lawyer decide whether to sue or negotiate, and what can actually be seized. We find verifiable asset leads from lawful sources and field work and hand them to your lawyer for the steps that require the court.",
    sections: [
      {
        heading: "Assets we trace and how",
        body: [],
        bullets: [
          "Real estate: houses, condominiums and land — from field visits, listings and the land-office channels available to interested parties",
          "Vehicles in actual use — from observation in public places",
          "Businesses: companies, directorships and shareholdings — from Thailand's public business registry",
          "Income sources and current workplace — from field visits and open sources",
          "Signs of assets transferred after a demand or lawsuit — for your lawyer to consider a fraudulent-transfer claim",
        ],
      },
      {
        heading: "Working with your lawyer",
        body: ["Some data, such as full title deeds or bank accounts, is available only to interested parties through the court or the Legal Execution Department. Our job is to produce complete, verifiable leads so your lawyer can file precisely, saving time and cost at the enforcement stage. We routinely work with Thai and foreign law firms."],
      },
      {
        heading: "Before suing vs. after judgment",
        body: ["Before suing: to decide whether litigation is worthwhile, and to plan interim measures. After judgment: to identify assets for seizure or garnishment and follow assets moved out of reach. The method is the same; the report is shaped to the stage you are at."],
      },
      {
        heading: "Cost",
        body: ["Depends on the number of debtors, the area and the depth of verification. Law firms and lenders usually work with us per case. You receive a written quote before we start."],
      },
    ],
    deliverables: [
      "Itemised asset leads with sources and how to verify each",
      "Photos of property and premises from field visits",
      "Company and directorship data from public sources",
      "A report formatted for your lawyer to file with",
      "Recommended order of enforcement steps",
    ],
    notOffered: [
      "Bank balances or account transactions",
      "Credit data or government database records",
      "Seizure, garnishment or debt collection on your behalf",
      "Entering private land or residences",
    ],
    faq: [
      { q: "Can you find the debtor's bank accounts?", a: "No. Bank data is protected and reachable only through the court or the Legal Execution Department. We can identify which banks a debtor appears to use from open sources, so your lawyer can target a garnishment order." },
      { q: "The debtor has already transferred assets. What now?", a: "We trace the transfers and the recipients so your lawyer can assess a claim to set the transfers aside under Thai law." },
      { q: "How long does it take?", a: "An initial asset trace usually takes a few days to two weeks depending on the area and the number of assets to verify." },
      { q: "Do you work with foreign law firms?", a: "Yes, regularly. We brief and report in English and format reports for use in Thai enforcement proceedings." },
    ],
    related: ["find-missing-person", "background-check", "pricing", "hire-a-private-detective"],
    caseType: "Asset search",
    priceNote: "Per-case written quote · 50 % deposit",
    counterpart: { th: "สืบทรัพย์สิน", zh: "asset-investigation" },
  },
  {
    lang: "en",
    slug: "cyber-investigation",
    kind: "service",
    service: "cyber",
    title: "Online Investigation Thailand — Scams & Fake Profiles",
    description: "Lawful online investigations in Thailand: verify who is behind a profile, trace online scammers, organise digital evidence. Open sources only, no hacking.",
    h1: "Cyber & Online Investigations — Within the Law",
    eyebrow: "Case File · Online Investigation",
    intro: "Who is really behind the profile you are talking to? Is the account that messaged you genuine? Where did the money you sent end up? We answer these questions with open-source intelligence (OSINT) and analysis of publicly visible digital traces, without hacking, interception or access to anyone's accounts.",
    sections: [
      {
        heading: "What we take on",
        body: [],
        bullets: [
          "Verifying whether a social-media account is genuine, fake or using stolen photos",
          "Tracing the people behind online scams from accounts, numbers and public data, to support a police report",
          "Checking unknown phone numbers against public scam reports",
          "Organising online evidence (screenshots, links, timestamps) so it is traceable and usable",
          "Reviewing the publicly visible online behaviour of a person or business",
        ],
      },
      {
        heading: "Legal boundaries",
        body: ["We use only information that is publicly visible or that you own. We do not guess passwords, send phishing links, intercept messages or buy data from illegal sources. Those acts breach Thailand's Computer Crime Act and PDPA and would make any evidence unusable."],
      },
      {
        heading: "Scammed online? Do this first",
        body: ["Contact your bank immediately to try to freeze onward transfers; in Thailand the anti-online-scam hotline is 1441. Keep every piece of evidence: slips, conversations, profiles, numbers and destination accounts. File a police report (Thai Police online reporting is available). We then help trace the people involved to strengthen the case."],
      },
    ],
    deliverables: [
      "Identity-verification report and account linkage analysis",
      "Organised online evidence with timestamps and sources",
      "Summary of the traces found from open sources",
      "Advice on reporting and on preventing a repeat",
    ],
    notOffered: [
      "Hacking, password guessing or access to anyone's accounts",
      "Message interception or telephone data from operators",
      "Locating another person's phone",
      "Buying personal data from illegal sources",
    ],
    faq: [
      { q: "Can you identify an online scammer?", a: "In many cases we can trace accounts, numbers and public data far enough to help the case, but we cannot promise identification every time. We assess first." },
      { q: "Can you get my money back?", a: "Freezing and recovering funds is a process run by banks and the authorities. We strengthen that process with evidence and traces." },
      { q: "Can you tell whether a profile is a real person?", a: "Yes. We analyse photo consistency, posting history, network and other open data and give a reasoned opinion." },
      { q: "Can you check my partner's Facebook or LINE?", a: "Only what is publicly visible. We never access another person's private accounts. For behaviour, see our infidelity service, which works lawfully in public places." },
    ],
    related: ["find-missing-person", "background-check", "investigate-partner-before-marriage", "pricing"],
    caseType: "Cyber / online",
    priceNote: "Free assessment · Written quote before we start",
    counterpart: { th: "นักสืบไอที" },
  },
  {
    lang: "en",
    slug: "hire-a-private-detective",
    kind: "info",
    service: "hire",
    title: "Hire a Private Detective in Thailand — How It Works",
    description: "How to hire a private investigator in Thailand from abroad or locally: the 8-step process, what to prepare, payment, and signs of a fake detective.",
    h1: "How to Hire a Private Detective in Thailand",
    eyebrow: "Case File · Hiring Guide",
    intro: "Hiring an investigator for the first time, often from another country, raises practical questions: where to start, what to share, how to pay safely, and how to tell a genuine agency from a scam. This page walks through our whole process and the warning signs worth knowing before you send money to anyone.",
    sections: [
      {
        heading: "The 8-step process",
        body: [],
        bullets: [
          "Contact us on WhatsApp, email or the form — free and without obligation. Describe the situation and what you need to know.",
          "We assess feasibility and the lawful scope, honestly, including when we think the case is not worth your money.",
          "You receive a written quote with scope, timeline and what is included.",
          "A 50 % deposit by bank transfer confirms the start.",
          "We plan the assignment: team, days, locations, and how you want updates.",
          "Field work and research run; you receive updates on the agreed schedule, in your time zone.",
          "You settle the balance and receive the report with photos, video and a timeline, electronically.",
          "We advise on next steps and, where useful, brief your lawyer.",
        ],
      },
      {
        heading: "What to prepare",
        body: ["The subject's name and photos, address or neighbourhood, workplace, vehicle, approximate routine, what you suspect and what you need to know, and your end goal (legal action, negotiation, or simply the truth). These shape the plan and the price."],
      },
      {
        heading: "Six warning signs of a fake or unlawful investigator",
        body: [],
        bullets: [
          "Promises to \"check anything\", including bank, phone or government data on other people",
          "Demands full payment before discussing details, or pressure to pay immediately",
          "No verifiable presence: no reviews on an independent platform, no video call",
          "Guarantees of a result or of \"catching them for sure\"",
          "Prices far below what the days and people required would cost",
          "Suggests unlawful methods such as trackers on other people's cars or phone hacking",
        ],
      },
      {
        heading: "How to check us",
        body: ["Read our identity-verified reviews on Fastwork, note that this site has run in Thai, English and Chinese for years, ask for a video call before starting, and always ask for a written quote. We say plainly when something cannot be done lawfully or is not worth the cost."],
      },
    ],
    deliverables: [
      "Written quote before anything starts",
      "A clear plan and timeline",
      "Updates during the assignment in your time zone",
      "Factual report with evidence, formatted for a lawyer when needed",
    ],
    faq: [
      { q: "Is the first consultation free?", a: "Yes. Feasibility and scope are assessed free of charge before we quote." },
      { q: "Do I need to be in Thailand?", a: "No. Most international clients brief us on WhatsApp or email, pay by transfer and receive the report electronically. A meeting in Bangkok or a video call is available if you prefer." },
      { q: "How do I pay from abroad?", a: `International bank transfer or PayPal; we provide the details with the written quote. We never ask for payment in gift cards or crypto.` },
      { q: "Can I cancel?", a: "Yes, but the deposit is non-refundable once field work has started. This is stated in every quote." },
    ],
    related: ["pricing", "cheating-spouse-investigator", "background-check", "private-investigator-bangkok"],
    caseType: "Other",
    priceNote: "Free consultation · Written quote before we start",
    counterpart: { th: "จ้างนักสืบ" },
  },
  {
    lang: "en",
    slug: "pricing",
    kind: "info",
    service: "pricing",
    title: "Private Investigator Cost in Thailand — How Pricing Works",
    description: "What a private investigator costs in Thailand depends on case type, days, team and location. Our pricing structure, 50 % deposit and how to get a quote.",
    h1: "Private Investigator Pricing in Thailand — A Transparent Structure",
    eyebrow: "Case File · Pricing",
    intro: "\"It depends\" does not help you decide. This page explains what our price is made of, which factors push it up or down, and how you get a firm written quote in the first conversation.",
    sections: [
      {
        heading: "What determines the price",
        body: [],
        bullets: [
          "Case type: observation uses more people and time than research-based verification",
          "Days or hours of observation required, and when (nights, weekends)",
          "Number of investigators needed to keep the assignment safe and unnoticed",
          "Location: Bangkok and its suburbs versus provinces with travel and accommodation",
          "Complexity, such as a cautious subject or several locations to verify",
        ],
      },
      {
        heading: "Payment and terms",
        body: ["A written quote is issued before every assignment. A 50 % deposit confirms the start and the balance is settled before the report is released. If the client cancels after field work has begun, the deposit is not refunded because the team has already deployed. Field costs driven by the subject's behaviour, such as venue entry, are agreed in advance as included or itemised."],
      },
      {
        heading: "What is included",
        body: [],
        bullets: [
          "Planning and a team sized to the agreed scope",
          "Observation or verification for the days specified",
          "Progress updates during the assignment",
          "A factual report with photos, video and a timeline",
          "A follow-up conversation about next steps after the report",
        ],
      },
      {
        heading: "Why a very low price is a warning sign",
        body: ["Safe observation needs at least one or two people per day with a vehicle. A price below that cost usually means work that is not actually done, or methods that break the law, which make the evidence unusable and can expose you to liability."],
      },
      {
        heading: "Paying from abroad",
        body: [`International bank transfer or PayPal. Details come with the written quote. We never ask for payment by gift card or cryptocurrency, and we never ask for full payment before the quote is agreed.`],
      },
    ],
    faq: [
      { q: "Can you give a rough price on chat?", a: `Yes. Most assignments start ${FACTS.confirmed.priceFrom.en}; once we know the case type, location and approximate days we give a range at once, and a firm written quote follows once we have the full picture.` },
      { q: "Are there hidden costs?", a: "No. Every cost that may arise is listed in the quote as included or itemised." },
      { q: "Which payment methods do you accept?", a: `${paymentMethodsText("en").replace(/^./, (c) => c.toUpperCase())}. Details come with the written quote; clients abroad can pay by PayPal.` },
      { q: "If you find nothing, do I still pay in full?", a: "Yes. You pay for the work performed to plan, not for a particular result. A \"nothing found\" result is equally valuable information, and we never embellish findings to make an assignment look worthwhile." },
    ],
    related: ["hire-a-private-detective", "cheating-spouse-investigator", "asset-investigation", "contact"],
    caseType: "Other",
    priceNote: "Free quote · 50 % deposit · No hidden costs",
    counterpart: { th: "ราคานักสืบ", zh: "pricing" },
  },
  {
    lang: "en",
    slug: "private-investigator-bangkok",
    kind: "location",
    service: "location",
    title: "Private Investigator in Bangkok — Local Team, Fast Start",
    description: "Bangkok-based private investigators covering every district and nearby provinces: infidelity, background checks, locating people, asset tracing.",
    h1: "Private Investigator in Bangkok — A Resident Team That Knows the City",
    eyebrow: "Location · Bangkok",
    intro: "Bangkok is where we work every day. A resident team that knows the districts, routes and traffic rhythms plans observation more precisely and starts faster than anywhere else. We cover all Bangkok districts and the surrounding provinces of Nonthaburi, Pathum Thani and Samut Prakan.",
    sections: [
      {
        heading: "Assignments we handle most in Bangkok",
        body: [],
        bullets: [
          "Infidelity and behaviour observation in business and residential districts",
          "Background checks on employees, partners and counterparties based in Bangkok",
          "Locating the current address of a debtor or a person a lawyer needs to serve",
          "Confirming that a company registered at an office address actually operates",
          "Verifying people met online who say they live or work in Bangkok",
        ],
      },
      {
        heading: "Areas we cover daily",
        body: ["Sukhumvit, Silom, Sathorn, Ratchada, Lat Phrao, Ramkhamhaeng, Bang Na, the Thonburi side and the surrounding provinces. Work around gated condominiums and housing estates is done from public areas only, and rush-hour traffic is built into the plan from the start."],
      },
      {
        heading: "How fast can you start?",
        body: ["Research-based verification starts as soon as the assignment is agreed. Most field assignments in Bangkok can be staffed within 1–2 working days; ask about urgent cases. You can meet us in Bangkok to discuss details or brief us on WhatsApp from anywhere."],
      },
      {
        heading: "Outside Bangkok and nationwide",
        body: ["We take assignments in every province, with travel and accommodation itemised in the quote. Cases where the subject moves between Bangkok and the provinces are planned as one continuous assignment."],
      },
    ],
    deliverables: [
      "A plan that accounts for real districts and traffic",
      "A resident team that deploys quickly",
      "Factual report with photos, video and timeline",
      "Choice of an in-person meeting in Bangkok or a fully remote briefing",
    ],
    notOffered: [
      "Entering condominiums, housing estates or other private premises",
      "GPS trackers or devices on other people's property",
      "Access to government, bank or telephone data on other people",
    ],
    faq: [
      { q: "Do you only cover Bangkok?", a: "No, we work nationwide, but Bangkok and its suburbs start fastest because the team is resident." },
      { q: "The subject lives in a guarded condominium. Can you still work?", a: "Yes, by observing from public areas around the building and its access routes. We never enter private premises." },
      { q: "Can we meet in person?", a: "Yes, in Bangkok at a place convenient for you, or we can start on WhatsApp or a video call right away." },
      { q: "Are the suburbs priced like Bangkok?", a: "Generally yes. Some outer areas carry a small travel charge, which is stated in the quote." },
    ],
    related: ["cheating-spouse-investigator", "background-check", "find-missing-person", "pricing"],
    caseType: "Other",
    priceNote: "Bangkok rates · Written quote before we start",
    counterpart: { th: "นักสืบกรุงเทพ", zh: "bangkok" },
  },
  {
    lang: "en",
    slug: "about",
    kind: "info",
    service: "about",
    title: `About Us — Private Investigators in Thailand Since ${YEAR}`,
    description: `A Thai private investigation agency working within the law since ${YEAR} for individuals, lawyers and businesses, in Thai, English and Chinese, nationwide.`,
    h1: "Who We Are and How We Work",
    eyebrow: "Dossier · About",
    intro: `Detective Pulse has provided private investigation services in Thailand since ${YEAR} for individuals, lawyers and businesses, many of them abroad. We believe good investigative work must be lawful, verifiable and reported honestly — including when the finding is "nothing unusual"`,
    sections: [
      {
        heading: "What we do",
        body: [`Infidelity and behaviour observation, background checks, locating people, asset tracing, online investigations and company verification. The core team is based in Bangkok and we take assignments nationwide.`, `The firm is led by ${FACTS.pending.leadInvestigator?.name ?? "its founder"}, ${FACTS.pending.leadInvestigator?.role.en.toLowerCase() ?? "founder"}, with a team of ${FACTS.confirmed.teamSize} investigators and support staff.`],
      },
      {
        heading: "How we work",
        body: [],
        bullets: [
          "Lawfully: observation in public places, open sources, field visits and documents provided by the client only, in line with Thailand's PDPA",
          "Honestly: we assess feasibility before accepting a case and decline work that cannot or should not be done",
          "Verifiably: every report records dates, times, places and sources",
          "Confidentially: client identity and findings are accessible only to the team responsible",
          "Without guarantees of outcome: we sell work to plan, not promises we cannot keep",
        ],
      },
      {
        heading: "Working with international clients",
        body: ["Most overseas clients brief us on WhatsApp or email, pay by international transfer, receive updates in their time zone and get the report electronically. We work in English, Thai and Chinese and regularly support foreign lawyers with Thai evidence."],
      },
      {
        heading: "How to check us",
        body: ["Read our identity-verified reviews on Fastwork, note that this site has run in three languages for years, ask for a video call before starting, and always ask for a written quote. If someone uses our name but proposes unlawful methods, it is not us."],
      },
    ],
    faq: [
      { q: "Do you have an office I can visit?", a: officeAnswer("en") },
      { q: "Do you work outside Bangkok?", a: "Yes, nationwide, with travel and accommodation itemised in the quote." },
      { q: "Do you work with lawyers and companies?", a: "Yes, they are a key client group, especially for asset tracing, locating people and background checks." },
      { q: "How long do you keep client data?", a: "Only as long as the assignment and our agreement require; it is deleted on schedule or on request within the law." },
    ],
    related: ["hire-a-private-detective", "pricing", "private-investigator-bangkok", "contact"],
    caseType: "Other",
    priceNote: "Free consultation · Confidential",
    counterpart: { th: "เกี่ยวกับเรา", zh: "about" },
  },
  {
    lang: "en",
    slug: "how-it-works",
    kind: "info",
    service: "how_it_works",
    title: "How a Private Investigation in Thailand Works — Step by Step",
    description: "How a case runs from first message to report: assessment, written quote, 50 % deposit, field work, updates in your time zone, and what the report contains.",
    h1: "How It Works — A Remote Case From First Message to Report",
    eyebrow: "Case File · How it works",
    intro: "Most of our clients have never hired an investigator, and many are thousands of kilometres from Thailand. This page explains plainly what happens after you contact us, who does what, how long it takes, what you see along the way and what the report looks like.",
    sections: [
      {
        heading: "The six steps",
        body: [],
        bullets: [
          "Initial consultation (free): tell us the situation, what you suspect and what you need to know, on WhatsApp, email or the form",
          "Feasibility assessment: we say plainly what can be done lawfully, what information we still need, and whether the case is worth your money",
          "Written quote: scope, days, team, what is included and excluded, and the timeline",
          "Start after the 50 % deposit: a day-by-day plan around the subject's routine; the team deploys or research begins",
          "Updates during the assignment: on the schedule we agree (daily summaries or key events), in your time zone",
          "Report and next steps: you settle the balance, receive the report with evidence, and we discuss what to do next",
        ],
      },
      {
        heading: "What the report contains",
        body: ["Every report records the date, time, place and source of each fact, separates what was observed from what was concluded, and is formatted so your lawyer can use it directly."],
        bullets: [
          "A one-page summary that answers the questions you asked",
          "An event timeline with photos and video from public places",
          "Findings from open sources and field visits, each with its source",
          "Limitations: what could not be confirmed and why",
          "Recommended next steps (legal, negotiation or further observation)",
        ],
      },
      {
        heading: "Working from abroad",
        body: ["You never need to come to Thailand. Briefing happens on WhatsApp or email, payment by international bank transfer with details on the written quote, updates arrive in your time zone and the report is delivered electronically. Many clients involve their own lawyer at home; we are used to briefing them."],
      },
      {
        heading: "What to prepare",
        body: ["The subject's name and photos, address or neighbourhood, workplace, vehicle, approximate routine and the questions you need answered. The more precise the information, the shorter the plan and the lower the price. What you don't have, we can often establish in a preliminary check."],
      },
      {
        heading: "Legal boundaries at every step",
        body: ["We observe in public places, use open sources, visit addresses and work with documents you provide. We do not enter private premises, place devices on other people's property, access protected accounts or data, or approach the subject. Work that cannot be done within those limits is declined at the assessment stage."],
      },
    ],
    deliverables: [
      "Written quote and plan",
      "Updates during the assignment on the agreed schedule",
      "Report with evidence, timeline and sources",
      "A follow-up conversation about next steps",
    ],
    faq: [
      { q: "Do I need to meet you first?", a: "No. Most cases are briefed on WhatsApp or email. A meeting in Bangkok or a video call is available if you prefer." },
      { q: "How will I know what is happening?", a: "On the schedule in the quote, for example an evening summary each day, or immediately when something significant happens." },
      { q: "What if you find nothing?", a: "We report honestly. A \"nothing found\" result is equally valuable information, and you pay for the work performed to plan, not for a particular outcome." },
      { q: "Can I see a sample report?", a: "Yes. Ask for a redacted sample during the consultation." },
    ],
    related: ["hire-a-private-detective", "pricing", "cheating-spouse-investigator", "contact"],
    caseType: "Other",
    priceNote: "Free consultation · Written quote · 50 % deposit",
    counterpart: { th: "ขั้นตอนการทำงาน", zh: "how-it-works" },
    sampleReport: true,
  },
  {
    lang: "en",
    slug: "due-diligence-thailand",
    kind: "service",
    service: "due_diligence",
    title: "Due Diligence in Thailand — Verify a Company or Partner",
    description: "Independent checks on Thai companies, suppliers and partners: registration, directors, litigation, real premises and reputation from public sources.",
    h1: "Due Diligence in Thailand — Know Who You Are Doing Business With",
    eyebrow: "Case File · Due Diligence",
    intro: "Before you wire an investment, sign a supply contract or take on a partner in Thailand, an independent check answers the basic questions: does this company exist, who is behind it, what trouble has it had, and does the story you were told match reality. We use public sources and visit premises in person, then report what can be verified.",
    sections: [
      {
        heading: "What we verify",
        body: [],
        bullets: [
          "Legal status, registered capital, directors, shareholders and filed financial statements from Thailand's public business registry (DBD)",
          "Real premises: whether the stated office or factory operates, at what scale, confirmed by a site visit with photos",
          "Publicly visible litigation and disputes involving the company and its directors",
          "Related companies through shared directors and shareholders",
          "Background and reputation of the principals from open sources and discreet industry enquiries",
          "Common red flags: virtual addresses, a young company claiming a long track record, guaranteed returns, pressure to pay quickly",
        ],
      },
      {
        heading: "Typical assignments",
        body: [],
        bullets: [
          "Checking a company that has invited you to invest or promised high returns",
          "Vetting a supplier or contractor before a large deposit",
          "Verifying a prospective joint-venture partner",
          "Checking a counterparty in a lease, property or franchise deal",
          "Confirming a Thai company for a foreign buyer, bank or law firm",
        ],
      },
      {
        heading: "What the report cannot do",
        body: ["We do not access bank, tax or internal company data that is not public, and we do not give legal or financial opinions in place of your advisers. Our report is verifiable fact, so your lawyer and accountant decide on fuller information."],
      },
      {
        heading: "Timeline and pricing",
        body: ["Registry-based checks start immediately and usually complete within a few working days; site visits add time per location. Pricing is per case by number of entities and depth. You receive a written quote before we start, and we report in English."],
      },
    ],
    deliverables: [
      "Factual company report with a source for every item",
      "Site-visit photos and notes at the real premises",
      "Director, shareholder and related-company map",
      "Red-flag summary and consistency with the counterparty's claims",
      "Points your lawyer or accountant should look at next",
    ],
    notOffered: [
      "Bank, tax or non-public internal data",
      "Legal opinions or financial valuations",
      "Pretexting as a customer or authority to extract information",
      "Access to the target company's systems or email",
    ],
    faq: [
      { q: "Can you check a foreign company operating in Thailand?", a: "Yes, for the part registered or operating in Thailand. For the overseas part we use that country's public sources as far as they are accessible and state the limits clearly." },
      { q: "How long does it take?", a: "A registry-based check usually completes within a few working days; site visits add time depending on locations and provinces." },
      { q: "How is this different from pulling the DBD record myself?", a: "The registry is the starting point. We add the site visit, litigation search, related-company map, principals' reputation and a comparison with what the counterparty claimed, which is where problems usually appear." },
      { q: "Is it confidential?", a: "Yes. The target company does not learn of the check, and the client's identity is confidential." },
    ],
    related: ["background-check", "asset-investigation", "for-law-firms", "pricing"],
    caseType: "Background check",
    priceNote: "Per-case pricing · Written quote before we start",
    counterpart: { th: "ตรวจสอบธุรกิจและคู่ค้า", zh: "business-due-diligence" },
  },
  {
    lang: "en",
    slug: "surveillance-thailand",
    kind: "service",
    service: "surveillance",
    title: "Surveillance in Thailand — Lawful, Professional Observation",
    description: "Discreet surveillance in public places for family, employment, insurance and commercial matters. Timestamped photo and video, timeline, court-ready report.",
    h1: "Surveillance in Thailand — Systematic Observation in Public Places",
    eyebrow: "Case File · Surveillance",
    intro: "Surveillance means observing where a person goes, whom they meet and what they do in public, and recording it as verifiable evidence. Beyond infidelity cases it supports custody disputes, employment and insurance matters, commercial disputes and checks on field staff, in Thailand and for clients abroad.",
    sections: [
      {
        heading: "When it is used",
        body: [],
        bullets: [
          "Family matters: a spouse's conduct, or the environment a child is being cared for in, to support a custody application",
          "Employment: an employee on sick leave working elsewhere, or working for a competitor during a contract",
          "Insurance: confirming a claimant's actual condition in public (for insurers and law firms)",
          "Commercial: a counterparty or former employee suspected of breaching a non-compete",
          "Personal: confirming what someone says they do with observable facts",
        ],
      },
      {
        heading: "How we work",
        body: ["We plan from the subject's routine, district and routes, and field at least one or two investigators with a vehicle per day so the subject is neither lost nor alerted. Events are recorded with time and location from public places only, and reported on the agreed schedule, in your time zone."],
      },
      {
        heading: "Legal boundaries",
        body: ["We observe only in public places or where there is no reasonable expectation of privacy. We do not enter homes, condominiums or closed premises, do not place GPS or recording devices on other people's property, do not intercept communications and never approach the subject. Those acts are offences in Thailand and would make all the evidence unusable."],
      },
      {
        heading: "Pricing and duration",
        body: ["Priced by days or hours, team size, time of day and location. Assignments are usually planned as a 3–7 day block around the subject's routine; single-day assignments for a specific date are possible. You receive a written quote before we start."],
      },
    ],
    deliverables: [
      "Timestamped photos and video from public places",
      "Timeline of events, locations and people met",
      "Daily field notes",
      "A summary report your lawyer can use",
      "Advice on whether to continue observing",
    ],
    notOffered: [
      "GPS or recording devices on other people's vehicles or property",
      "Entering private premises or filming into a residence",
      "Interception of calls or messages, or phone access",
      "Approaching, provoking or confronting the subject",
    ],
    faq: [
      { q: "Will the subject notice?", a: "The team works discreetly in public and never approaches the subject. No assignment is entirely risk-free, and we say where the risks are before we start." },
      { q: "How many consecutive days can you cover?", a: "As many as the plan requires, usually a 3–7 day block adjusted to what we find. We stop as soon as the question is answered." },
      { q: "Do you work for insurers and law firms?", a: "Yes, and we format reports for use in proceedings." },
      { q: "Outside Bangkok?", a: "Nationwide. Travel and accommodation are itemised in the quote." },
    ],
    related: ["cheating-spouse-investigator", "how-it-works", "for-law-firms", "pricing"],
    caseType: "Other",
    priceNote: "Priced by days and team · Written quote before we start",
    counterpart: { th: "ติดตามพฤติกรรม" },
  },
  {
    lang: "en",
    slug: "romance-scam-investigation",
    kind: "service",
    service: "romance_scam",
    title: "Romance Scam Investigation Thailand — Is Your Partner Real?",
    description: "Verify an online partner in Thailand before sending more money: who is behind the profile, whether they are where they say, and where your transfers went.",
    h1: "Romance Scam Investigation — Find Out Who Is Really Behind the Profile",
    eyebrow: "Case File · Romance Scam",
    intro: "Someone you met online says they live in Thailand. The relationship feels real, but there have been requests for money, reasons you can never visit, and a video call that never quite happens. We verify the identity behind the profile and whether the person and the story exist on the ground, using open sources and field visits, so you can decide on facts.",
    sections: [
      {
        heading: "Signs clients report",
        body: ["No single sign proves anything; clients usually contact us when several appear together."],
        bullets: [
          "Requests for money for a medical bill, a customs fee, a visa, a family emergency or a business opportunity",
          "Excuses that prevent video calls or meeting in person",
          "A profile whose photos appear elsewhere under another name",
          "A story that shifts: job, city, family details",
          "Pressure to move the conversation to a private app quickly",
        ],
      },
      {
        heading: "What we can establish",
        body: [],
        bullets: [
          "Whether the photos and profile belong to a real person, or are taken from someone else",
          "Whether a person of that name and description lives and works where claimed, confirmed by visiting",
          "Whether the destination accounts for your transfers appear in public scam reports",
          "Whether a claimed business, hospital stay or customs problem is consistent with public facts",
          "If the person is real: their actual circumstances, as far as can be observed lawfully in public",
        ],
      },
      {
        heading: "If you have already sent money",
        body: ["Contact your bank at once to attempt to stop onward transfers, keep every slip, chat and profile, and report to the police in your country and, where Thai accounts are involved, to Thailand's anti-online-scam hotline 1441. Recovery is run by banks and authorities; our role is evidence and tracing that gives those processes weight. We cannot promise recovery and will tell you plainly when the chances are low."],
      },
      {
        heading: "What we never do",
        body: ["We do not contact the person, do not access their accounts or phone, do not pay anyone for data and do not pose as you. Everything comes from open sources and lawful observation."],
      },
    ],
    deliverables: [
      "Identity-verification report with reasoning and sources",
      "Field confirmation of the claimed address or workplace, with photos where appropriate",
      "Organised evidence pack (profiles, chats, transfers) for a police report",
      "A plain assessment: real person, uncertain, or scam indicators",
      "Advice on reporting and protecting yourself",
    ],
    notOffered: [
      "Contacting or confronting the person",
      "Accessing their accounts, phone or messages",
      "Recovering funds — a bank and law-enforcement process",
      "Buying personal data from illegal sources",
    ],
    faq: [
      { q: "Can you tell me quickly whether it is a scam?", a: "Often an initial open-source check within a few days gives a strong indication. Field confirmation in Thailand follows if needed." },
      { q: "I'm embarrassed. Is this confidential?", a: "Completely. Many of our clients are in the same situation. Your identity and the findings stay between you and us." },
      { q: "Can you find the scammer and get my money back?", a: "We can often trace accounts, numbers and public data far enough to help a police report, but recovery is run by banks and the authorities and we cannot promise it." },
      { q: "What if the person turns out to be real?", a: "Then you learn their actual circumstances and can decide with facts. We report honestly either way." },
    ],
    related: ["investigate-partner-before-marriage", "cyber-investigation", "find-missing-person", "pricing"],
    caseType: "Cyber / online",
    priceNote: "Free assessment · Written quote before we start",
  },
  {
    lang: "en",
    slug: "for-law-firms",
    kind: "info",
    service: "law_firms",
    title: "Investigators for Law Firms in Thailand — Court-Ready Facts",
    description: "Case support for Thai and foreign law firms: asset tracing for enforcement, locating defendants and witnesses, surveillance and site verification.",
    h1: "For Law Firms — Field Facts You Can Put Before a Court",
    eyebrow: "Partner Programme · Law Firms",
    intro: "Lawyers need facts that are traceable, delivered on time and obtained lawfully. We work with Thai and foreign law firms per case or on an ongoing basis, from pre-litigation asset tracing to locating a defendant for service, and every report records its sources and how each fact was obtained.",
    sections: [
      {
        heading: "What law firms use us for",
        body: [],
        bullets: [
          "Asset tracing before suing and before enforcement, with leads precise enough to file on",
          "Locating defendants, witnesses or heirs for service or contact",
          "Surveillance in family, employment and insurance matters",
          "Background and credibility checks on witnesses or opposing parties from open sources",
          "Due diligence on an opposing party's companies and network",
          "Site verification with photographs for property, construction and accident matters",
        ],
      },
      {
        heading: "Why firms work with us",
        body: [],
        bullets: [
          "Every item dated, timed, located and sourced; reports formatted for filing",
          "Strictly lawful scope, which minimises admissibility risk and exposure for counsel",
          "Fast assessment and quotes; urgent matters accepted",
          "Confidentiality and a conflict check before every engagement",
          "English-language reporting and direct contact for the firm; invoicing on agreed terms",
        ],
      },
      {
        heading: "How we work together",
        body: ["Per case: a written quote for each matter, suited to occasional use. Ongoing: fixed terms and rates for recurring work types, a direct channel and the same report standard every time. Foreign firms typically brief us by email and receive reports electronically; we are used to coordinating with Thai co-counsel. Contact us to arrange a call."],
      },
      {
        heading: "What we do not do",
        body: ["We do not access data that requires a court order, such as a party's bank or telephone data, do not approach witnesses in a way that could be seen as influencing them, and do not give legal opinions. Our job is field fact for you to use."],
      },
    ],
    deliverables: [
      "Factual report with sources and the method of obtaining each fact",
      "Photos, video and timelines from public places",
      "Asset leads in a form suitable for enforcement applications",
      "Direct contact and agreed response times",
    ],
    faq: [
      { q: "Can your investigator testify?", a: "Where necessary, yes. The investigator who obtained the evidence can speak to how it was obtained and the accuracy of the record, on terms agreed in advance." },
      { q: "Do you run conflict checks?", a: "Yes. Before accepting a matter we confirm we are not acting for the other side in the same dispute." },
      { q: "Can you take urgent matters?", a: "Yes, especially in Bangkok and its suburbs. Tell us the deadline and we assess at once." },
      { q: "Can you invoice the firm and work on account?", a: "Yes, and payment terms can be agreed for ongoing work." },
    ],
    related: ["asset-investigation", "find-missing-person", "surveillance-thailand", "due-diligence-thailand"],
    caseType: "Other",
    priceNote: "Per case or ongoing terms · Written quote before we start",
    counterpart: { th: "สำหรับทนายความ" },
  },
  {
    lang: "en",
    slug: "case-studies",
    kind: "info",
    service: "case_studies",
    title: "Private Investigator Case Studies Thailand — Anonymised",
    description: "Anonymised case studies from real investigations in Thailand: situation, objective, high-level approach, deliverables and outcome, so you see how we work.",
    h1: "Case Studies — Real Cases, Fully Anonymised",
    eyebrow: "Exhibits · Case studies",
    intro: "Every case here comes from real work, is published with the client's consent, and has every name, place, vehicle, phone number and identifying detail removed. The point is to show how we work, not to show tactics.",
    sections: [
      {
        heading: "How to read a case study",
        body: ["Each case follows the same structure: the client's situation, objective, challenges, high-level approach, deliverables, outcome and lessons. One case's outcome is never a promise for the next; every assignment depends on different facts and starting information."],
      },
      {
        heading: "Why some cases end with \"nothing unusual found\"",
        body: ["We report honestly. Many clients learn that what they suspected is not true, and that peace of mind is exactly what they paid for, so the case studies include both kinds of result."],
      },
    ],
    faq: [
      { q: "Can I see a case similar to mine?", a: "Yes. Tell us the type of matter during the consultation and we will explain the approach from similar cases without disclosing any other client's details." },
      { q: "Will my case be published?", a: "No, unless you give written consent, and even then with every identifying detail removed." },
      { q: "Can I get a sample report?", a: "Yes. Ask for a redacted sample during the consultation." },
    ],
    related: ["how-it-works", "cheating-spouse-investigator", "asset-investigation", "contact"],
    caseType: "Other",
    priceNote: "Free consultation · Confidential",
    counterpart: { th: "กรณีศึกษา", zh: "case-studies" },
    caseStudies: true,
  },
];
